### ISSUE TITLE
ac-clang sometimes no response

### ISSUE THREAD

**Issue by zijianyue** [yaruopooner/ac-clang#9] opened 2016-04-05 07:49 UTC
no response I mean smart-jump and code completion don't work ,
run ac-clang-reboot-server will recover,but after a while the problem happen again.

**Comment by yaruopooner** [comment] 2017-10-13 17:02
I'm sorry.
I did not notice the issue.
We plan to settle this problem by December.
Currently ac-clang is planning to upgrade major version,
It will be resolved in that version upgrade.

**Comment by yaruopooner** [comment] 2017-10-13 17:04
The cause is identified,
It has been resolved in the development version.

**Closed as completed** 2017-11-24 06:15 UTC

**Comment by yaruopooner** [comment] 2017-12-03 17:35
This problem was solved with the latest version.
ClangServer version 2.0.0
ac-clang versin 2.0.0
